# docker-compose.yml
version: '3'
services:
  parrot_ido:
    image: parrot-ido
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '127.0.0.1:3010:3000'
    command: yarn dev
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: 10m
    volumes:
      - ./:/app